# Generated by Django 5.2.7 on 2025-12-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statystyki', '0001_initial'),
        ('integracja_uzytkownika', '0004_auto_20251206_1719')
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION aktualizuj_statystyki_po_progress()
                RETURNS TRIGGER AS $$
                BEGIN
                    IF OLD.status = 'W' AND NEW.status IN ('OP', 'OZ') THEN
                        INSERT INTO statystyki_statystykipytania (pytanie_id, ilosc_odpowiedzi, poprawne_odpowiedzi)
                        VALUES (NEW.pytanie_id, 0, 0)
                        ON CONFLICT (pytanie_id) DO NOTHING;
                        
                        IF NEW.status = 'OP' THEN
                            UPDATE statystyki_statystykipytania
                            SET ilosc_odpowiedzi = ilosc_odpowiedzi + 1,
                                poprawne_odpowiedzi = poprawne_odpowiedzi + 1
                            WHERE pytanie_id = NEW.pytanie_id;
                        ELSE
                            UPDATE statystyki_statystykipytania
                            SET ilosc_odpowiedzi = ilosc_odpowiedzi + 1
                            WHERE pytanie_id = NEW.pytanie_id;
                        END IF;
                    END IF;
                    
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS aktualizuj_statystyki_po_progress();"
        ),
        
        migrations.RunSQL(
            sql="""
                DROP TRIGGER IF EXISTS trigger_aktualizuj_statystyki ON integracja_uzytkownika_progresspytan;
                
                CREATE TRIGGER trigger_aktualizuj_statystyki
                AFTER UPDATE ON integracja_uzytkownika_progresspytan
                FOR EACH ROW
                EXECUTE FUNCTION aktualizuj_statystyki_po_progress();
            """,
            reverse_sql="DROP TRIGGER IF EXISTS trigger_aktualizuj_statystyki ON integracja_uzytkownika_progresspytan;"
        ),
        
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION aktualizuj_statystyki_po_insert_progress()
                RETURNS TRIGGER AS $$
                BEGIN
                    IF NEW.status IN ('OP', 'OZ') THEN
                        INSERT INTO statystyki_statystykipytania (pytanie_id, ilosc_odpowiedzi, poprawne_odpowiedzi)
                        VALUES (NEW.pytanie_id, 0, 0)
                        ON CONFLICT (pytanie_id) DO NOTHING;
                        
                        IF NEW.status = 'OP' THEN
                            UPDATE statystyki_statystykipytania
                            SET ilosc_odpowiedzi = ilosc_odpowiedzi + 1,
                                poprawne_odpowiedzi = poprawne_odpowiedzi + 1
                            WHERE pytanie_id = NEW.pytanie_id;
                        ELSE
                            UPDATE statystyki_statystykipytania
                            SET ilosc_odpowiedzi = ilosc_odpowiedzi + 1
                            WHERE pytanie_id = NEW.pytanie_id;
                        END IF;
                    END IF;
                    
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;
                
                DROP TRIGGER IF EXISTS trigger_aktualizuj_statystyki_insert ON integracja_uzytkownika_progresspytan;
                
                CREATE TRIGGER trigger_aktualizuj_statystyki_insert
                AFTER INSERT ON integracja_uzytkownika_progresspytan
                FOR EACH ROW
                EXECUTE FUNCTION aktualizuj_statystyki_po_insert_progress();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS trigger_aktualizuj_statystyki_insert ON integracja_uzytkownika_progresspytan;
                DROP FUNCTION IF EXISTS aktualizuj_statystyki_po_insert_progress();
            """
        ),
    ]
