# Generated by Django 5.2.7 on 2026-01-01 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statystyki', '0003_auto_20251206_1805'),
        ('integracja_uzytkownika', '0004_auto_20251206_1719'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION aktualizuj_statystyki_po_progress()
                RETURNS TRIGGER AS $$
                BEGIN
                    IF OLD.status IN ('W','NW') AND NEW.status IN ('OP', 'OZ') THEN
                        INSERT INTO statystyki_statystykipytania (pytanie_id, ilosc_odpowiedzi, poprawne_odpowiedzi)
                        VALUES (NEW.pytanie_id, 0, 0)
                        ON CONFLICT (pytanie_id) DO NOTHING;
                        
                        IF NEW.status = 'OP' THEN
                            UPDATE statystyki_statystykipytania
                            SET ilosc_odpowiedzi = ilosc_odpowiedzi + 1,
                                poprawne_odpowiedzi = poprawne_odpowiedzi + 1
                            WHERE pytanie_id = NEW.pytanie_id;
                        ELSE
                            UPDATE statystyki_statystykipytania
                            SET ilosc_odpowiedzi = ilosc_odpowiedzi + 1
                            WHERE pytanie_id = NEW.pytanie_id;
                        END IF;
                    END IF;
                    
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS aktualizuj_statystyki_po_progress();"
        ),
        
    ]
