# Generated by Django 5.2.7 on 2026-01-21 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statystyki', '0004_auto_20260101_2227'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE statystyki_statystykipytania DROP CONSTRAINT IF EXISTS statystyki_statystykipytania_pytanie_id_fkey;
            ALTER TABLE statystyki_statystykipytania ADD CONSTRAINT statystyki_statystykipytania_pytanie_id_fkey FOREIGN KEY (pytanie_id) REFERENCES kursy_pytanie(id) ON DELETE CASCADE;
            """,
            reverse_sql="""
            ALTER TABLE statystyki_statystykipytania DROP CONSTRAINT IF EXISTS statystyki_statystykipytania_pytanie_id_fkey;
            ALTER TABLE statystyki_statystykipytania ADD CONSTRAINT statystyki_statystykipytania_pytanie_id_fkey FOREIGN KEY (pytanie_id) REFERENCES kursy_pytanie(id) ON DELETE RESTRICT;
            """
        ),
    ]
