# Generated by Django 5.2.7 on 2025-12-06 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integracja_uzytkownika', '0002_delete_statystykipytania'),
    ]

    operations = [
        migrations.RunSQL(
            sql=""" 
                CREATE VIEW average_grade_for_users_kurs_view AS
                SELECT avg(we.wynik) AS avg,
                we.kurs_id,
                we.uzytkownik_id,
                u.username
                FROM integracja_uzytkownika_wynikiegzaminu we
                JOIN auth_user u ON u.id = we.uzytkownik_id
                GROUP BY we.uzytkownik_id, we.kurs_id, u.username
                ORDER BY we.uzytkownik_id; """,
            reverse_sql="""
                DROP VIEW average_grade_for_users_kurs_view;
                """
        ),
        migrations.RunSQL(
            sql="""
                CREATE VIEW avg_kurs_grade AS
                SELECT round(avg(wynik)::numeric, 2) AS avg_wynik,
                kurs_id
                FROM integracja_uzytkownika_wynikiegzaminu we
                GROUP BY kurs_id;
                """,
            reverse_sql="""
                DROP VIEW avg_kurs_grade;
                """),
        
        migrations.RunSQL(
            sql=""" 
                CREATE VIEW kursy_ukonczone_ostatnie_7_dni AS
                SELECT d.d::date AS dzien,
                count(i.id) AS liczba_kursow
                FROM generate_series((now() - '6 days'::interval)::date::timestamp with time zone, now()::date::timestamp with time zone, '1 day'::interval) d(d)
                LEFT JOIN integracja_uzytkownika_wynikiegzaminu i ON i.data_zapisu::date = d.d::date
                GROUP BY d.d
                ORDER BY d.d;
            """,
            reverse_sql="""
                DROP VIEW kursy_ukonczone_ostatnie_7_dni;
                """),

        migrations.RunSQL(
            sql="""
                CREATE VIEW leaderboard AS
                SELECT round(avg(w.wynik)::numeric, 2) AS srednia,
                u.username
                FROM integracja_uzytkownika_wynikiegzaminu w
                JOIN auth_user u ON w.uzytkownik_id = u.id
                GROUP BY u.username
                HAVING avg(w.wynik) >= 50::double precision AND count(*) >= 10
                ORDER BY (round(avg(w.wynik)::numeric, 2)) DESC
                LIMIT 3;
                """,
            reverse_sql="""
                DROP VIEW leaderboard;
                """),
        migrations.RunSQL(
            sql="""
                CREATE VIEW zapis_uzytkownika_view AS
                SELECT p.id,
                p.data_zapisu,
                a.tresc,
                a.tytul,
                p.uzytkownik_id,
                p.artykul_id
                FROM integracja_uzytkownika_zapisartykulu p
                JOIN kursy_artykul a ON a.id = p.artykul_id;""",
            reverse_sql="""
                DROP VIEW zapis_uzytkownika_view;
                """),
       
    ]
