# Generated by Django 5.2.7 on 2025-12-06 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integracja_uzytkownika', '0003_auto_20251206_1613'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE integracja_uzytkownika_wynikiegzaminu
                ADD CONSTRAINT wynik_egzaminu_zakres 
                CHECK (wynik >= 0.0 AND wynik <=100.0);
                """,
            reverse_sql="""
                ALTER TABLE integracja_uzytkownika_wynikiegzaminu
                DROP CONSTRAINT wynik_egzaminu_zakres;
                """
        ),

        migrations.RunSQL(
            sql="""
                ALTER TABLE integracja_uzytkownika_ocenaartykulu
                ADD CONSTRAINT ocena_zakres 
                CHECK (ocena >= 1 and ocena <= 5);
                """,
            reverse_sql="""
                ALTER TABLE integracja_uzytkownika_ocenaartykulu
                DROP CONSTRAINT ocena_zakres;
                """
        ),
    ]
