# Generated by Django 5.2.7 on 2026-01-21 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integracja_uzytkownika', '0004_auto_20251206_1719'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE integracja_uzytkownika_zapisartykulu DROP CONSTRAINT IF EXISTS integracja_uzytkownika_z_artykul_id_fk_kursy_art;
            ALTER TABLE integracja_uzytkownika_zapisartykulu ADD CONSTRAINT integracja_uzytkownika_z_artykul_id_fk_kursy_art FOREIGN KEY (artykul_id) REFERENCES kursy_artykul(id) ON DELETE CASCADE;
            ALTER TABLE integracja_uzytkownika_zapisartykulu DROP CONSTRAINT IF EXISTS integracja_uzytkownika_z_uzytkownik_id_fk_auth_use;
            ALTER TABLE integracja_uzytkownika_zapisartykulu ADD CONSTRAINT integracja_uzytkownika_z_uzytkownik_id_fk_auth_use FOREIGN KEY (uzytkownik_id) REFERENCES auth_user(id) ON DELETE CASCADE;

            ALTER TABLE integracja_uzytkownika_notatka DROP CONSTRAINT IF EXISTS integracja_uzytkownika_n_artykul_id_fk_kursy_art;
            ALTER TABLE integracja_uzytkownika_notatka ADD CONSTRAINT integracja_uzytkownika_n_artykul_id_fk_kursy_art FOREIGN KEY (artykul_id) REFERENCES kursy_artykul(id) ON DELETE CASCADE;
            ALTER TABLE integracja_uzytkownika_notatka DROP CONSTRAINT IF EXISTS integracja_uzytkownika_n_uzytkownik_id_fk_auth_use;
            ALTER TABLE integracja_uzytkownika_notatka ADD CONSTRAINT integracja_uzytkownika_n_uzytkownik_id_fk_auth_use FOREIGN KEY (uzytkownik_id) REFERENCES auth_user(id) ON DELETE CASCADE;

            ALTER TABLE integracja_uzytkownika_komentarz DROP CONSTRAINT IF EXISTS integracja_uzytkownika_k_artykul_id_fk_kursy_art;
            ALTER TABLE integracja_uzytkownika_komentarz ADD CONSTRAINT integracja_uzytkownika_k_artykul_id_fk_kursy_art FOREIGN KEY (artykul_id) REFERENCES kursy_artykul(id) ON DELETE CASCADE;
            ALTER TABLE integracja_uzytkownika_komentarz DROP CONSTRAINT IF EXISTS integracja_uzytkownika_k_uzytkownik_id_fk_auth_use;
            ALTER TABLE integracja_uzytkownika_komentarz ADD CONSTRAINT integracja_uzytkownika_k_uzytkownik_id_fk_auth_use FOREIGN KEY (uzytkownik_id) REFERENCES auth_user(id) ON DELETE CASCADE;

            ALTER TABLE integracja_uzytkownika_progresspytan DROP CONSTRAINT IF EXISTS integracja_uzytkownika_p_pytanie_id_fk_kursy_pyt;
            ALTER TABLE integracja_uzytkownika_progresspytan ADD CONSTRAINT integracja_uzytkownika_p_pytanie_id_fk_kursy_pyt FOREIGN KEY (pytanie_id) REFERENCES kursy_pytanie(id) ON DELETE CASCADE;
            ALTER TABLE integracja_uzytkownika_progresspytan DROP CONSTRAINT IF EXISTS integracja_uzytkownika_p_uzytkownik_id_fk_auth_use;
            ALTER TABLE integracja_uzytkownika_progresspytan ADD CONSTRAINT integracja_uzytkownika_p_uzytkownik_id_fk_auth_use FOREIGN KEY (uzytkownik_id) REFERENCES auth_user(id) ON DELETE CASCADE;

            ALTER TABLE integracja_uzytkownika_wynikiegzaminu DROP CONSTRAINT IF EXISTS integracja_uzytkownika_w_kurs_id_fk_kursy_kur;
            ALTER TABLE integracja_uzytkownika_wynikiegzaminu ADD CONSTRAINT integracja_uzytkownika_w_kurs_id_fk_kursy_kur FOREIGN KEY (kurs_id) REFERENCES kursy_kurs(id) ON DELETE CASCADE;
            ALTER TABLE integracja_uzytkownika_wynikiegzaminu DROP CONSTRAINT IF EXISTS integracja_uzytkownika_w_uzytkownik_id_fk_auth_use;
            ALTER TABLE integracja_uzytkownika_wynikiegzaminu ADD CONSTRAINT integracja_uzytkownika_w_uzytkownik_id_fk_auth_use FOREIGN KEY (uzytkownik_id) REFERENCES auth_user(id) ON DELETE CASCADE;

            ALTER TABLE integracja_uzytkownika_ocenaartykulu DROP CONSTRAINT IF EXISTS integracja_uzytkownika_o_artykul_id_fk_kursy_art;
            ALTER TABLE integracja_uzytkownika_ocenaartykulu ADD CONSTRAINT integracja_uzytkownika_o_artykul_id_fk_kursy_art FOREIGN KEY (artykul_id) REFERENCES kursy_artykul(id) ON DELETE CASCADE;
            ALTER TABLE integracja_uzytkownika_ocenaartykulu DROP CONSTRAINT IF EXISTS integracja_uzytkownika_o_uzytkownik_id_fk_auth_use;
            ALTER TABLE integracja_uzytkownika_ocenaartykulu ADD CONSTRAINT integracja_uzytkownika_o_uzytkownik_id_fk_auth_use FOREIGN KEY (uzytkownik_id) REFERENCES auth_user(id) ON DELETE CASCADE;
            """,
            reverse_sql="""
            ALTER TABLE integracja_uzytkownika_zapisartykulu DROP CONSTRAINT IF EXISTS integracja_uzytkownika_z_artykul_id_fk_kursy_art;
            ALTER TABLE integracja_uzytkownika_zapisartykulu ADD CONSTRAINT integracja_uzytkownika_z_artykul_id_fk_kursy_art FOREIGN KEY (artykul_id) REFERENCES kursy_artykul(id) ON DELETE RESTRICT;
            ALTER TABLE integracja_uzytkownika_zapisartykulu DROP CONSTRAINT IF EXISTS integracja_uzytkownika_z_uzytkownik_id_fk_auth_use;
            ALTER TABLE integracja_uzytkownika_zapisartykulu ADD CONSTRAINT integracja_uzytkownika_z_uzytkownik_id_fk_auth_use FOREIGN KEY (uzytkownik_id) REFERENCES auth_user(id) ON DELETE RESTRICT;

            ALTER TABLE integracja_uzytkownika_notatka DROP CONSTRAINT IF EXISTS integracja_uzytkownika_n_artykul_id_fk_kursy_art;
            ALTER TABLE integracja_uzytkownika_notatka ADD CONSTRAINT integracja_uzytkownika_n_artykul_id_fk_kursy_art FOREIGN KEY (artykul_id) REFERENCES kursy_artykul(id) ON DELETE RESTRICT;
            ALTER TABLE integracja_uzytkownika_notatka DROP CONSTRAINT IF EXISTS integracja_uzytkownika_n_uzytkownik_id_fk_auth_use;
            ALTER TABLE integracja_uzytkownika_notatka ADD CONSTRAINT integracja_uzytkownika_n_uzytkownik_id_fk_auth_use FOREIGN KEY (uzytkownik_id) REFERENCES auth_user(id) ON DELETE RESTRICT;

            ALTER TABLE integracja_uzytkownika_komentarz DROP CONSTRAINT IF EXISTS integracja_uzytkownika_k_artykul_id_fk_kursy_art;
            ALTER TABLE integracja_uzytkownika_komentarz ADD CONSTRAINT integracja_uzytkownika_k_artykul_id_fk_kursy_art FOREIGN KEY (artykul_id) REFERENCES kursy_artykul(id) ON DELETE RESTRICT;
            ALTER TABLE integracja_uzytkownika_komentarz DROP CONSTRAINT IF EXISTS integracja_uzytkownika_k_uzytkownik_id_fk_auth_use;
            ALTER TABLE integracja_uzytkownika_komentarz ADD CONSTRAINT integracja_uzytkownika_k_uzytkownik_id_fk_auth_use FOREIGN KEY (uzytkownik_id) REFERENCES auth_user(id) ON DELETE RESTRICT;

            ALTER TABLE integracja_uzytkownika_progresspytan DROP CONSTRAINT IF EXISTS integracja_uzytkownika_p_pytanie_id_fk_kursy_pyt;
            ALTER TABLE integracja_uzytkownika_progresspytan ADD CONSTRAINT integracja_uzytkownika_p_pytanie_id_fk_kursy_pyt FOREIGN KEY (pytanie_id) REFERENCES kursy_pytanie(id) ON DELETE RESTRICT;
            ALTER TABLE integracja_uzytkownika_progresspytan DROP CONSTRAINT IF EXISTS integracja_uzytkownika_p_uzytkownik_id_fk_auth_use;
            ALTER TABLE integracja_uzytkownika_progresspytan ADD CONSTRAINT integracja_uzytkownika_p_uzytkownik_id_fk_auth_use FOREIGN KEY (uzytkownik_id) REFERENCES auth_user(id) ON DELETE RESTRICT;

            ALTER TABLE integracja_uzytkownika_wynikiegzaminu DROP CONSTRAINT IF EXISTS integracja_uzytkownika_w_kurs_id_fk_kursy_kur;
            ALTER TABLE integracja_uzytkownika_wynikiegzaminu ADD CONSTRAINT integracja_uzytkownika_w_kurs_id_fk_kursy_kur FOREIGN KEY (kurs_id) REFERENCES kursy_kurs(id) ON DELETE RESTRICT;
            ALTER TABLE integracja_uzytkownika_wynikiegzaminu DROP CONSTRAINT IF EXISTS integracja_uzytkownika_w_uzytkownik_id_fk_auth_use;
            ALTER TABLE integracja_uzytkownika_wynikiegzaminu ADD CONSTRAINT integracja_uzytkownika_w_uzytkownik_id_fk_auth_use FOREIGN KEY (uzytkownik_id) REFERENCES auth_user(id) ON DELETE RESTRICT;

            ALTER TABLE integracja_uzytkownika_ocenaartykulu DROP CONSTRAINT IF EXISTS integracja_uzytkownika_o_artykul_id_fk_kursy_art;
            ALTER TABLE integracja_uzytkownika_ocenaartykulu ADD CONSTRAINT integracja_uzytkownika_o_artykul_id_fk_kursy_art FOREIGN KEY (artykul_id) REFERENCES kursy_artykul(id) ON DELETE RESTRICT;
            ALTER TABLE integracja_uzytkownika_ocenaartykulu DROP CONSTRAINT IF EXISTS integracja_uzytkownika_o_uzytkownik_id_fk_auth_use;
            ALTER TABLE integracja_uzytkownika_ocenaartykulu ADD CONSTRAINT integracja_uzytkownika_o_uzytkownik_id_fk_auth_use FOREIGN KEY (uzytkownik_id) REFERENCES auth_user(id) ON DELETE RESTRICT;
            """
        ),
    ]
