# Generated by Django 5.2.7 on 2025-10-24 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artykul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
                ('tytul', models.CharField(max_length=200)),
                ('nr_artykulu', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_kursu', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pytanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
                ('artykul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kursy.artykul')),
            ],
        ),
        migrations.CreateModel(
            name='Odpowiedz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
                ('poprawna', models.BooleanField(default=False)),
                ('pytanie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kursy.pytanie')),
            ],
        ),
        migrations.CreateModel(
            name='Rozdzial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_rozdzialu', models.CharField(max_length=50)),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kursy.kurs')),
            ],
        ),
        migrations.AddField(
            model_name='artykul',
            name='rozdzial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kursy.rozdzial'),
        ),
        migrations.CreateModel(
            name='Uzytkownik_kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zapisu', models.DateTimeField(auto_now_add=True)),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kursy.kurs')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('uzytkownik', 'kurs')},
            },
        ),
        migrations.AddField(
            model_name='kurs',
            name='uzytkownik',
            field=models.ManyToManyField(through='kursy.Uzytkownik_kurs', to=settings.AUTH_USER_MODEL),
        ),
    ]
