# Generated by Django 5.2.7 on 2025-10-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursy', '0003_alter_artykul_nr_artykulu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artykul',
            name='tytul',
            field=models.TextField(),
        ),
    ]
