# Generated by Django 5.2.7 on 2025-12-06 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kursy', '0006_remove_notatka_artykul_remove_notatka_uzytkownik_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE VIEW artykul_kurs_view AS
                SELECT 
                    av.id AS artykul_id,
                    av.tresc,
                    k.nazwa_kursu,
                    k.id AS kurs_id 
                FROM 
                    kursy_artykul av
                JOIN 
                    kursy_rozdzial k_r ON av.rozdzial_id = k_r.id
                JOIN 
                    kursy_kurs k ON k.id = k_r.kurs_id;
            """,
            
            reverse_sql="""
                DROP VIEW artykul_kurs_view;
            """
        ),
        migrations.RunSQL(
            sql="""
                CREATE VIEW artykul_rozdzial_view AS
                SELECT 
                    av.artykul_id,
                    a.tytul,
                    av.tresc,
                    av.nazwa_kursu,
                    av.kurs_id,      -- Zmieniono na kurs_id (używane jako ID kursu w poprzednim widoku)
                    a.rozdzial_id
                FROM 
                    artykul_kurs_view av -- <--- Używa widoku stworzonego powyżej
                JOIN 
                    kursy_artykul a ON av.artykul_id = a.id;
            """,
            
            reverse_sql="""
                DROP VIEW artykul_rozdzial_view;
            """
        ),

        migrations.RunSQL(
            sql="""
                CREATE VIEW pytanie_artykul_view AS
                SELECT p.id AS pytanie_id,
                p.tresc AS tresc_pytania,
                a.id AS artykul_id,
                a.tytul AS artykul_tytul,
                a.tresc AS artykul_tresc,
                o.id AS odpowiedz_id,
                o.tresc AS tresc_odpowiedzi,
                o.poprawna AS czy_poprawna
            FROM kursy_pytanie p
                JOIN kursy_artykul a ON p.artykul_id = a.id
                JOIN kursy_odpowiedz o ON o.pytanie_id = p.id;
     """,
            reverse_sql=""" 
                DROP VIEW pytanie_artykul_view;
                """
        ),

        migrations.RunSQL(
            sql=""" 
                CREATE VIEW quiz_view AS
                 SELECT p.id AS pytanie_id,
    p.tresc AS pytanie_tresc,
    o.id AS odpowiedz_id,
    o.tresc AS odpowiedz_tresc,
    o.poprawna
   FROM kursy_pytanie p
     JOIN kursy_odpowiedz o ON o.pytanie_id = p.id;
     """,
            reverse_sql="""
                DROP VIEW quiz_view;
                """
        ),
    ]
