# Generated by Django 5.2.7 on 2025-12-06 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kursy', '0007_auto_20251206_1609'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE UNIQUE INDEX jedna_poprawna_odpowiedz
                ON kursy_odpowiedz (pytanie_id)
                WHERE poprawna = TRUE;
            """,
            
            reverse_sql="""
                DROP INDEX jedna_poprawna_odpowiedz;
            """
        ),

        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION sprawdz_limit_odpowiedzi()
                RETURNS TRIGGER AS $$
                DECLARE 
                    liczba_odpowiedzi INTEGER;
                BEGIN
                    SELECT COUNT(*) into liczba_odpowiedzi
                    FROM kursy_odpowiedz
                    where pytanie_id = NEW.pytanie_id;

                    IF liczba_odpowiedzi >= 4 THEN
                        RAISE EXCEPTION 'Blad limitu odpowiedzi. Pytanie o ID % ma juz maksymalna ilosc odpowiedzi', NEW.id_pytania
                        USING HINT = 'Usun istniejaca odpowiedz przed dodaniem nowej.';
                    END IF;

                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER przed_wstawieniem_odpowiedzi
                BEFORE INSERT ON kursy_odpowiedz
                FOR EACH ROW
                EXECUTE FUNCTION sprawdz_limit_odpowiedzi();
            """,
            
            reverse_sql="""
                DROP TRIGGER IF EXISTS przed_wstawieniem_odpowiedzi ON kursy_odpowiedz;
                DROP FUNCTION IF EXISTS sprawdz_limit_odpowiedzi();
            """
        ),
        
    ]
