# Generated by Django 5.2.7 on 2025-11-21 19:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kursy', '0006_remove_notatka_artykul_remove_notatka_uzytkownik_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Komentarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
                ('data_zapisu', models.DateTimeField(auto_now_add=True)),
                ('artykul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kursy.artykul')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Komentarz',
                'verbose_name_plural': 'Komentarze',
                'ordering': ['-data_zapisu'],
            },
        ),
        migrations.CreateModel(
            name='Notatka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
                ('data_zapisu', models.DateTimeField(auto_now_add=True)),
                ('artykul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kursy.artykul')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notatka',
                'verbose_name_plural': 'Notatki',
                'ordering': ['-data_zapisu'],
            },
        ),
        migrations.CreateModel(
            name='StatystykiPytania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc_odpowiedzi', models.PositiveIntegerField(default=0)),
                ('poprawne_odpowiedzi', models.PositiveIntegerField(default=0)),
                ('pytanie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kursy.pytanie')),
            ],
            options={
                'verbose_name': 'Statystyka Pytania',
                'verbose_name_plural': 'Statystyki pytania',
            },
        ),
        migrations.CreateModel(
            name='WynikiEgzaminu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zapisu', models.DateTimeField(auto_now_add=True)),
                ('wynik', models.FloatField()),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kursy.kurs')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wynik egzaminu',
                'verbose_name_plural': 'Wyniki egzaminów',
                'ordering': ['-data_zapisu'],
            },
        ),
        migrations.CreateModel(
            name='OcenaArtykulu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('artykul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kursy.artykul')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('uzytkownik', 'artykul')},
            },
        ),
        migrations.CreateModel(
            name='ProgressPytan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NW', 'Nie wyswietlone'), ('W', 'Wyswietlone'), ('OP', 'Poprawna odpowiedz'), ('OZ', 'Niepoprawna odpowiedz')], default='NW', max_length=2)),
                ('data_aktualizacji', models.DateTimeField(auto_now=True)),
                ('pytanie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kursy.pytanie')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Postęp pytania',
                'verbose_name_plural': 'Postępy pytań',
                'ordering': ['-data_aktualizacji'],
                'unique_together': {('uzytkownik', 'pytanie')},
            },
        ),
        migrations.CreateModel(
            name='ZapisArtykulu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zapisu', models.DateTimeField(auto_now_add=True)),
                ('artykul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kursy.artykul')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ZapisArtykulu',
                'verbose_name_plural': 'ZapisyArtykulu',
                'ordering': ['-data_zapisu'],
                'unique_together': {('uzytkownik', 'artykul')},
            },
        ),
    ]
