# Generated by Django 5.2.7 on 2025-11-21 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integracja_uzytkownika', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatystykiPytania',
        ),
    ]
