# Generated by Django 5.2.7 on 2025-10-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursy', '0002_alter_artykul_options_alter_kurs_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artykul',
            name='nr_artykulu',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='rozdzial',
            name='nazwa_rozdzialu',
            field=models.CharField(max_length=255),
        ),
    ]
