# Generated by Django 5.2.7 on 2025-11-21 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kursy', '0005_komentarz_notatka_statystykipytania_wynikiegzaminu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notatka',
            name='artykul',
        ),
        migrations.RemoveField(
            model_name='notatka',
            name='uzytkownik',
        ),
        migrations.AlterUniqueTogether(
            name='ocenaartykulu',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ocenaartykulu',
            name='artykul',
        ),
        migrations.RemoveField(
            model_name='ocenaartykulu',
            name='uzytkownik',
        ),
        migrations.AlterUniqueTogether(
            name='progresspytan',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='progresspytan',
            name='pytanie',
        ),
        migrations.RemoveField(
            model_name='progresspytan',
            name='uzytkownik',
        ),
        migrations.RemoveField(
            model_name='statystykipytania',
            name='pytanie',
        ),
        migrations.RemoveField(
            model_name='wynikiegzaminu',
            name='kurs',
        ),
        migrations.RemoveField(
            model_name='wynikiegzaminu',
            name='uzytkownik',
        ),
        migrations.AlterUniqueTogether(
            name='zapisartykulu',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='zapisartykulu',
            name='artykul',
        ),
        migrations.RemoveField(
            model_name='zapisartykulu',
            name='uzytkownik',
        ),
        migrations.DeleteModel(
            name='Komentarz',
        ),
        migrations.DeleteModel(
            name='Notatka',
        ),
        migrations.DeleteModel(
            name='OcenaArtykulu',
        ),
        migrations.DeleteModel(
            name='ProgressPytan',
        ),
        migrations.DeleteModel(
            name='StatystykiPytania',
        ),
        migrations.DeleteModel(
            name='WynikiEgzaminu',
        ),
        migrations.DeleteModel(
            name='ZapisArtykulu',
        ),
    ]
