# Generated by Django 5.2.7 on 2026-01-21 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kursy', '0008_auto_20251206_1640'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE kursy_uzytkownik_kurs DROP CONSTRAINT IF EXISTS kursy_uzytkownik_kurs_uzytkownik_id_fk_auth_user_id;
            ALTER TABLE kursy_uzytkownik_kurs ADD CONSTRAINT kursy_uzytkownik_kurs_uzytkownik_id_fk_auth_user_id FOREIGN KEY (uzytkownik_id) REFERENCES auth_user(id) ON DELETE CASCADE;

            ALTER TABLE kursy_uzytkownik_kurs DROP CONSTRAINT IF EXISTS kursy_uzytkownik_kurs_kurs_id_fk_kursy_kurs_id;
            ALTER TABLE kursy_uzytkownik_kurs ADD CONSTRAINT kursy_uzytkownik_kurs_kurs_id_fk_kursy_kurs_id FOREIGN KEY (kurs_id) REFERENCES kursy_kurs(id) ON DELETE CASCADE;

            ALTER TABLE kursy_rozdzial DROP CONSTRAINT IF EXISTS kursy_rozdzial_kurs_id_fk_kursy_kurs_id;
            ALTER TABLE kursy_rozdzial ADD CONSTRAINT kursy_rozdzial_kurs_id_fk_kursy_kurs_id FOREIGN KEY (kurs_id) REFERENCES kursy_kurs(id) ON DELETE CASCADE;

            ALTER TABLE kursy_artykul DROP CONSTRAINT IF EXISTS kursy_artykul_rozdzial_id_fk_kursy_rozdzial_id;
            ALTER TABLE kursy_artykul ADD CONSTRAINT kursy_artykul_rozdzial_id_fk_kursy_rozdzial_id FOREIGN KEY (rozdzial_id) REFERENCES kursy_rozdzial(id) ON DELETE CASCADE;

            ALTER TABLE kursy_pytanie DROP CONSTRAINT IF EXISTS kursy_pytanie_artykul_id_fk_kursy_artykul_id;
            ALTER TABLE kursy_pytanie ADD CONSTRAINT kursy_pytanie_artykul_id_fk_kursy_artykul_id FOREIGN KEY (artykul_id) REFERENCES kursy_artykul(id) ON DELETE CASCADE;

            ALTER TABLE kursy_odpowiedz DROP CONSTRAINT IF EXISTS kursy_odpowiedz_pytanie_id_fk_kursy_pytanie_id;
            ALTER TABLE kursy_odpowiedz ADD CONSTRAINT kursy_odpowiedz_pytanie_id_fk_kursy_pytanie_id FOREIGN KEY (pytanie_id) REFERENCES kursy_pytanie(id) ON DELETE CASCADE;
            """,
            reverse_sql="""
            ALTER TABLE kursy_uzytkownik_kurs DROP CONSTRAINT IF EXISTS kursy_uzytkownik_kurs_uzytkownik_id_fk_auth_user_id;
            ALTER TABLE kursy_uzytkownik_kurs ADD CONSTRAINT kursy_uzytkownik_kurs_uzytkownik_id_fk_auth_user_id FOREIGN KEY (uzytkownik_id) REFERENCES auth_user(id) ON DELETE RESTRICT;

            ALTER TABLE kursy_uzytkownik_kurs DROP CONSTRAINT IF EXISTS kursy_uzytkownik_kurs_kurs_id_fk_kursy_kurs_id;
            ALTER TABLE kursy_uzytkownik_kurs ADD CONSTRAINT kursy_uzytkownik_kurs_kurs_id_fk_kursy_kurs_id FOREIGN KEY (kurs_id) REFERENCES kursy_kurs(id) ON DELETE RESTRICT;

            ALTER TABLE kursy_rozdzial DROP CONSTRAINT IF EXISTS kursy_rozdzial_kurs_id_fk_kursy_kurs_id;
            ALTER TABLE kursy_rozdzial ADD CONSTRAINT kursy_rozdzial_kurs_id_fk_kursy_kurs_id FOREIGN KEY (kurs_id) REFERENCES kursy_kurs(id) ON DELETE RESTRICT;

            ALTER TABLE kursy_artykul DROP CONSTRAINT IF EXISTS kursy_artykul_rozdzial_id_fk_kursy_rozdzial_id;
            ALTER TABLE kursy_artykul ADD CONSTRAINT kursy_artykul_rozdzial_id_fk_kursy_rozdzial_id FOREIGN KEY (rozdzial_id) REFERENCES kursy_rozdzial(id) ON DELETE RESTRICT;

            ALTER TABLE kursy_pytanie DROP CONSTRAINT IF EXISTS kursy_pytanie_artykul_id_fk_kursy_artykul_id;
            ALTER TABLE kursy_pytanie ADD CONSTRAINT kursy_pytanie_artykul_id_fk_kursy_artykul_id FOREIGN KEY (artykul_id) REFERENCES kursy_artykul(id) ON DELETE RESTRICT;

            ALTER TABLE kursy_odpowiedz DROP CONSTRAINT IF EXISTS kursy_odpowiedz_pytanie_id_fk_kursy_pytanie_id;
            ALTER TABLE kursy_odpowiedz ADD CONSTRAINT kursy_odpowiedz_pytanie_id_fk_kursy_pytanie_id FOREIGN KEY (pytanie_id) REFERENCES kursy_pytanie(id) ON DELETE RESTRICT;
            """
        ),
    ]