# Generated by Django 5.2.7 on 2025-10-24 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kursy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artykul',
            options={'verbose_name': 'Artykul', 'verbose_name_plural': 'Artykuly'},
        ),
        migrations.AlterModelOptions(
            name='kurs',
            options={'verbose_name': 'Kurs', 'verbose_name_plural': 'Kursy'},
        ),
        migrations.AlterModelOptions(
            name='odpowiedz',
            options={'verbose_name': 'Odpowiedz', 'verbose_name_plural': 'Odpowiedzi'},
        ),
        migrations.AlterModelOptions(
            name='pytanie',
            options={'verbose_name': 'Pytanie', 'verbose_name_plural': 'Pytania'},
        ),
        migrations.AlterModelOptions(
            name='rozdzial',
            options={'verbose_name': 'Rozdzial', 'verbose_name_plural': 'Rozdzialy'},
        ),
        migrations.AlterModelOptions(
            name='uzytkownik_kurs',
            options={'verbose_name': 'Uzytkownik_kurs', 'verbose_name_plural': 'Uzytkownik_kursy'},
        ),
    ]
