# Generated by Django 5.2.7 on 2025-11-21 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kursy', '0006_remove_notatka_artykul_remove_notatka_uzytkownik_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatystykiPytania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc_odpowiedzi', models.PositiveIntegerField(default=0)),
                ('poprawne_odpowiedzi', models.PositiveIntegerField(default=0)),
                ('pytanie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kursy.pytanie')),
            ],
            options={
                'verbose_name': 'Statystyka Pytania',
                'verbose_name_plural': 'Statystyki pytania',
            },
        ),
    ]
