# Generated by Django 5.2.7 on 2025-12-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statystyki', '0002_add_progress_trigger'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE statystyki_statystykipytania
                ADD CONSTRAINT ilosc_odpowiedzi_pozytywna
                CHECK (ilosc_odpowiedzi >= 0);
            """,
            reverse_sql="""
                ALTER TABLE statystyki_statystykipytania
                DROP CONSTRAINT ilosc_odpowiedzi_pozytywna;
            """
        ),

        migrations.RunSQL(
            sql="""
                ALTER TABLE statystyki_statystykipytania
                ADD CONSTRAINT poprawne_odpowiedzi_pozytywna
                CHECK (poprawne_odpowiedzi >= 0);
            """,
            reverse_sql="""
                ALTER TABLE statystyki_statystykipytania
                DROP CONSTRAINT poprawne_odpowiedzi_pozytywna;
            """
        )
    ]
